name: piistech_weather_flutter_bloc
description: weather app
version: 3.0.0+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_fonts: ^2.1.0
  html: ^0.15.0
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  intl:
  collection:
  material_design_icons_flutter: ^5.0.6295
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
